package com.cassiezys.transaction.mapper;

import com.cassiezys.transaction.model.Operate;
import com.cassiezys.transaction.model.OperateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    long countByExample(OperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int deleteByExample(OperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int insert(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int insertSelective(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    List<Operate> selectByExampleWithRowbounds(OperateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    List<Operate> selectByExample(OperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    Operate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Operate record, @Param("example") OperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int updateByExample(@Param("record") Operate record, @Param("example") OperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int updateByPrimaryKeySelective(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbg.generated Sun Mar 22 12:28:28 CST 2020
     */
    int updateByPrimaryKey(Operate record);
}