package com.cassiezys.transaction.model;

public class Operate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.parent_id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.type
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.creator
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.status
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.gmt_create
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.gmt_modified
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.id
     *
     * @return the value of operate.id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.id
     *
     * @param id the value for operate.id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.parent_id
     *
     * @return the value of operate.parent_id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.parent_id
     *
     * @param parentId the value for operate.parent_id
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.type
     *
     * @return the value of operate.type
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.type
     *
     * @param type the value for operate.type
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.creator
     *
     * @return the value of operate.creator
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.creator
     *
     * @param creator the value for operate.creator
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.status
     *
     * @return the value of operate.status
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.status
     *
     * @param status the value for operate.status
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.gmt_create
     *
     * @return the value of operate.gmt_create
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.gmt_create
     *
     * @param gmtCreate the value for operate.gmt_create
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.gmt_modified
     *
     * @return the value of operate.gmt_modified
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.gmt_modified
     *
     * @param gmtModified the value for operate.gmt_modified
     *
     * @mbg.generated Sun Mar 22 15:13:47 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}