package com.cassiezys.transaction.model;

public class Production {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.id
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.title
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.gmt_create
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.gmt_modified
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.creator
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.comment_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.view_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.like_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.city
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.pic_url
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.price
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.origprice
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Float origprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.tele
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long tele;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.tencent
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private Long tencent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.wechat
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.address
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.payway
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String payway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.category
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production.description
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.id
     *
     * @return the value of production.id
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.id
     *
     * @param id the value for production.id
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.title
     *
     * @return the value of production.title
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.title
     *
     * @param title the value for production.title
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.gmt_create
     *
     * @return the value of production.gmt_create
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.gmt_create
     *
     * @param gmtCreate the value for production.gmt_create
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.gmt_modified
     *
     * @return the value of production.gmt_modified
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.gmt_modified
     *
     * @param gmtModified the value for production.gmt_modified
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.creator
     *
     * @return the value of production.creator
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.creator
     *
     * @param creator the value for production.creator
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.comment_count
     *
     * @return the value of production.comment_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.comment_count
     *
     * @param commentCount the value for production.comment_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.view_count
     *
     * @return the value of production.view_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.view_count
     *
     * @param viewCount the value for production.view_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.like_count
     *
     * @return the value of production.like_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.like_count
     *
     * @param likeCount the value for production.like_count
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.city
     *
     * @return the value of production.city
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.city
     *
     * @param city the value for production.city
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.pic_url
     *
     * @return the value of production.pic_url
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.pic_url
     *
     * @param picUrl the value for production.pic_url
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.price
     *
     * @return the value of production.price
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.price
     *
     * @param price the value for production.price
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.origprice
     *
     * @return the value of production.origprice
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Float getOrigprice() {
        return origprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.origprice
     *
     * @param origprice the value for production.origprice
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setOrigprice(Float origprice) {
        this.origprice = origprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.tele
     *
     * @return the value of production.tele
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.tele
     *
     * @param tele the value for production.tele
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setTele(Long tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.tencent
     *
     * @return the value of production.tencent
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public Long getTencent() {
        return tencent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.tencent
     *
     * @param tencent the value for production.tencent
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setTencent(Long tencent) {
        this.tencent = tencent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.wechat
     *
     * @return the value of production.wechat
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.wechat
     *
     * @param wechat the value for production.wechat
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.address
     *
     * @return the value of production.address
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.address
     *
     * @param address the value for production.address
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.payway
     *
     * @return the value of production.payway
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.payway
     *
     * @param payway the value for production.payway
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setPayway(String payway) {
        this.payway = payway == null ? null : payway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.category
     *
     * @return the value of production.category
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.category
     *
     * @param category the value for production.category
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production.description
     *
     * @return the value of production.description
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production.description
     *
     * @param description the value for production.description
     *
     * @mbg.generated Mon Feb 10 17:01:53 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}